### ISSUE TITLE
Use robust `orient2d` predicate

### ISSUE THREAD

**Issue by mourner** [JuliaGeometry/Delaunator.jl#14]
From the project's README:

> In comparison, the Delaunator.jl package seeks to mirror the javascript Delauantor packages that give good enough triangulations for many pixel-level graphics applications and are fast for 2d problems, rather than those that might be suitable for those with computational geometry applications that need better guarantees (although we do hope to improve this in the future).

This behavior no longer mirrors Delaunator in JS — the latter is using robust orient2d predicate as of v4 (see https://github.com/mapbox/delaunator/pull/68) to guarantee robust triangulation.

**Comment by dgleich** [comment]
Thanks for the comment and apologies about the confusion. The readme has been updated now. Hope we can get this improved to use the exact predicates sometime soon!

**Comment by asinghvi17** [comment]
https://github.com/vchuravy/AdaptivePredicates.jl/ covers the same surface as that JS library, so Delaunator could use that...

**Comment by dgleich** [comment]
Oh that's nice! I really would rather avoiding StaticArrays as a dependency -- and indeed, any dependencies at all :) 

Let me take a look at what it'd take to modify it to get to a point where we could use this.

**Comment by DanielVandH** [comment]
FYI @dgleich The rest of https://github.com/JuliaGeometry/AdaptivePredicates.jl has been ported over now in case you are interested on using it for `incircle` as well.
