### ISSUE TITLE
Publish first release... 

### ISSUE THREAD

**Issue by dgleich** [JuliaGeometry/Delaunator.jl#7]
what all do we need to do to push the first release? 

I got the docs in (better) shape. Added a fun picture today...

Tag and use Julia Registrator?

**Comment by dgleich** [comment]
@sjkelly anything else you want to do before pushing the first release?

**Comment by sjkelly** [comment]
It looks great!

**Comment by sjkelly** [comment]
FYI when you are ready, you can comment on a commit with `@juliaregistrator register()` to start the release process.

**Comment by juliohm** [comment]
Thank you both for yet another package for Delaunay triangles. Should VoronoiDelaunay.jl be deprecated and/or archived? Maybe we should add a note to the README of some package to explain the current situation in Julia Delaunay packages. There are tons of them at this point...

**Comment by dgleich** [comment]
That's a good idea... other packages... 

- [VoronoiDelaunay.jl](https://github.com/JuliaGeometry/VoronoiDelaunay.jl)
- [VoronoiCells.jl](https://github.com/JuliaGeometry/VoronoiCells.jl)
- [DirectQhull.jl](https://github.com/JuhaHeiskala/DirectQhull.jl)
- [DelaunayTriangulation.jl](https://github.com/DanielVandH/DelaunayTriangulation.jl)

What are still missing? 

At a high level...

VoronoiDelaunay: uses GeometricalPredicates and requires input in [1,2] range, fast 
VoronoiCells: post-processes VoronoiDelaunay output to get info on Voronoi dual cells. 
DirectQhull: A wrapper for Qhull's methods (slow), but very robust. 
DelaunayTriangulation: I've looked less at this one, uses ExactPredicates and has a variety of methods for triangulation. Less support for dual / Voronoi cells. 

Delaunator.jl includes support for clipping all of the Voronoi cells to a bounding box making it useful for a variety of graphics applications. It will exclude points if they are too close.

**Comment by juliohm** [comment]
MiniQHull.jl is yet another wrapper for the QHull library.

It would be nice to point out which pure Julia package is more likely to be maintained moving forward. The wrapper packages are useful for reference tests.

**Comment by dgleich** [comment]
Okay, I put in a new comment to the end of the readme.

**Comment by sjkelly** [comment]
Okay we finally got this through the registrator!

**Comment by dgleich** [comment]
Woohoo! Thanks for keeping an eye on it!
